name: workflow-docker-manual

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Enter tag name for test/dev image'
        default: 'test'

jobs:
fail-fast: false
  gcr-dockerhub-build-publish:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, ubuntu-latest, windows-2016, windows-2019, macos-10.15]
        #operating-system: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, ubuntu-latest, windows-2016, windows-2019, macos-10.15]
    steps:
      - name: echo pre GITHUB_REPOSITORY
        run: |
          echo "GITHUB_REPOSITORY $GITHUB_REPOSITORY"

      - name: downcase REPO
        run: |
          echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: echo post REPO
        run: |
          echo "REPO $REPO"

      - name: echo pre GITHUB_REPOSITORY
        run: |
          echo "GITHUB_REPOSITORY $GITHUB_REPOSITORY"

      - name: downcase GITHUB_REPOSITORY
        run: |
          echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}
          echo "GITHUB_REPOSITORY_LC=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      - name: echo post GITHUB_REPOSITORY
        run: |
          echo "GITHUB_REPOSITORY $GITHUB_REPOSITORY"

      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        if: secrets.DOCKERHUB_USERNAME != ''
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Login to GitLab
        uses: docker/login-action@v1
        if: ${{ secrets.GITLAB_USERNAME }} != ''
        with:
          registry: registry.gitlab.com
          username: ${{ secrets.GITLAB_USERNAME }}
          password: ${{ secrets.GITLAB_TOKEN }}
      - name: Show Runners environment (debug)
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            export
      - name: Generate temporary tag name
        shell: bash
        run: |
          test_tag=$(date +%Y%m%d%H%M%S)
          echo "[debug] Generated test tag name is '${test_tag}'"
          echo "::set-output name=test_tag::$test_tag"
        id: generate_temporary_tag_name
      - name: Generate app name
        shell: bash
        run: |
          app_name=$(echo "${GITHUB_REPOSITORY}" | grep -P -o -m 1 '(?<=/arch-).*')
          echo "[debug] Generated app name is '${app_name}'"
          echo "::set-output name=app_name::$app_name"
        id: generate_app_name
      - name: Env Fix LowerCase GITHUB_REPOSITORY repo_name_lc
        shell: bash
        run: |
          repo_name_lc=$(echo "${GITHUB_REPOSITORY}" | tr '[A-Z]' '[a-z]')
          repo_name_uc=$(echo "${GITHUB_REPOSITORY}" | tr '[a-z]' '[A-Z]')
          repo_name=$(echo "${GITHUB_REPOSITORY}")
          echo "[debug] Generated repo name lc is '${repo_name_lc}'"
          echo "[debug] Generated repo name uc is '${repo_name_uc}'"
          echo "[debug] Generated repo name is '${repo_name}'"
          echo "::set-output name=repo_name_lc::$repo_name_lc"
          echo "::set-output name=repo_name_uc::$repo_name_uc"
          echo "::set-output name=repo_name::$repo_name"
        id: env_fix

      - name: Build Docker image and tag
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 60
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            docker build \
              --tag ${{ steps.env_fix.outputs.repo_name_lc }}:${{ steps.generate_temporary_tag_name.outputs.test_tag }} \
              --tag ${{ steps.env_fix.outputs.repo_name_lc }}:${{ github.event.inputs.tags }} \
              --tag ghcr.io/${{ steps.env_fix.outputs.repo_name_lc }}:${{ steps.generate_temporary_tag_name.outputs.test_tag }} \
              --tag ghcr.io/${{ steps.env_fix.outputs.repo_name_lc }}:${{ github.event.inputs.tags }} \
              --tag registry.gitlab.com/${{ steps.env_fix.outputs.repo_name_lc }}:${{ steps.generate_temporary_tag_name.outputs.test_tag }} \
              --tag registry.gitlab.com/${{ steps.env_fix.outputs.repo_name_lc }}:${{ github.event.inputs.tags }} \
              .
      - name: Run Tests
        shell: bash
        run: |
          git_clone_scripts_dest="/tmp/scripts"
          git_clone_scripts_repo="https://github.com/binhex/scripts.git"

          git clone "${git_clone_scripts_repo}" "${git_clone_scripts_dest}"
          "${git_clone_scripts_dest}/shell/arch/docker/testrunner.sh" --app-name ${{ steps.generate_app_name.outputs.app_name }} --image-name "ghcr.io/${{ steps.env_fix.outputs.repo_name_lc }}:${{ steps.generate_temporary_tag_name.outputs.test_tag }}"
      - name: Push Docker image to Docker Hub
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 30
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            docker push ${{ steps.env_fix.outputs.repo_name_lc }}:${{ github.event.inputs.tags }}
      - name: Push Docker image to GitHub Container Registry (GHCR)
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 30
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            docker push ghcr.io/${{ steps.env_fix.outputs.repo_name_lc }}:${{ github.event.inputs.tags }}
      - name: Push Docker image to GitLab Container Registry (GCR)
        uses: nick-invision/retry@v2.4.0
        with:
          timeout_minutes: 30
          max_attempts: 3
          retry_wait_seconds: 120
          command: |
            docker push registry.gitlab.com/${{ steps.env_fix.outputs.repo_name_lc }}:${{ github.event.inputs.tags }}
